name: CI

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:

jobs:
  ci:
    uses: Volontariapp/ci-tools/.github/workflows/service-ci.yml@main
    with:
      service-name: ms-user
    secrets: inherit

  ci-docker:
    needs: ci
    permissions:
      contents: read
      packages: write
    uses: Volontariapp/ci-tools/.github/workflows/service-docker-build-push.yml@main
    with:
      service-name: ms-user
    secrets: inherit

  e2e:
    needs: [ci-docker]
    uses: Volontariapp/ci-tools/.github/workflows/e2e-orchestrator.yml@main
    secrets: inherit

  validate-e2e-matrix:
    uses: Volontariapp/ci-tools/.github/workflows/e2e-matrix-checker.yml@main
    with:
      service-name: ms-user
